apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    access: proxy
    database: mydb
    user: myuser
    secureJsonData:
      password: mypass
    isDefault: true
