version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: fastapi-backend
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASS: mypass
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: streamlit-frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"
    environment:
      API_URL: http://backend:8000

  airflow-init:
    image: apache/airflow:2.10.2
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://myuser:mypass@postgres/mydb
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://myuser:mypass@postgres/mydb
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    entrypoint: /bin/bash -c "airflow db init"

  airflow-webserver:
    image: apache/airflow:2.10.2
    depends_on:
      - airflow-init
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://myuser:mypass@postgres/mydb
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://myuser:mypass@postgres/mydb
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    command: >
      bash -c "airflow db upgrade && airflow users create --username admin --password admin123 --firstname Admin --lastname User --role Admin --email admin@example.com && airflow webserver"


  airflow-scheduler:
    image: apache/airflow:2.10.2
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://myuser:mypass@postgres/mydb
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    command: scheduler

  airflow-worker:
    image: apache/airflow:2.10.2
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://myuser:mypass@postgres/mydb
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    command: celery worker

  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - backend

volumes:
  pgdata:
